### ISSUE TITLE
Pretty error when VM is missing

### ISSUE THREAD

**Issue by TomMD** [myoung34/vagrant-ovirt3#42]
I used vagrant to add a machine then the OVirt web interface to delete it.  Eventually I wanted to rebuild the machine, forgetting about the prior and with the `.vagrant` still laying around.  This sequence of operations results in an unhandled exception that should be caught and pretty-printed:

```
/Users/tommd/.vagrant.d/gems/gems/rbovirt-0.1.0/lib/rbovirt.rb:198:in `handle_fault': 404 Resource Not Found (OVIRT::OvirtException)
        from /Users/tommd/.vagrant.d/gems/gems/rbovirt-0.1.0/lib/rbovirt.rb:115:in `rescue in http_get'
        from /Users/tommd/.vagrant.d/gems/gems/rbovirt-0.1.0/lib/rbovirt.rb:110:in `http_get'
        from /Users/tommd/.vagrant.d/gems/gems/rbovirt-0.1.0/lib/client/vm_api.rb:5:in `vm'
        from /Users/tommd/.vagrant.d/gems/gems/fog-1.37.0/lib/fog/ovirt/requests/compute/get_virtual_machine.rb:6:in `get_virtual_machine'
        from /Users/tommd/.vagrant.d/gems/gems/fog-1.37.0/lib/fog/ovirt/models/compute/servers.rb:15:in `get'
        from /Users/tommd/.vagrant.d/gems/gems/vagrant-ovirt3-1.5.0/lib/vagrant-ovirt3/action/read_state.rb:25:in `read_state'
        from /Users/tommd/.vagrant.d/gems/gems/vagrant-ovirt3-1.5.0/lib/vagrant-ovirt3/action/read_state.rb:15:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from /Users/tommd/.vagrant.d/gems/gems/vagrant-ovirt3-1.5.0/lib/vagrant-ovirt3/action/connect_ovirt.rb:71:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
...
```

**Comment by myoung34** [comment]
Fixed in `1.6.2`
